import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    colorHeader:{
        backgroundColor:'#2A78E2'
    },
    sizeHeader:{
        flex:1,
        marginTop:10,
        marginLeft:5
    },
    iconApple:{
        fontSize:14,
        color:'white'
    },
    textRank:{
        textAlign:'right',
        color:'#90477B',
        fontSize:15,
        marginBottom:5
    },
    textUsername:{
        textAlign:'right',
        fontSize:15,
        color:'#90477B',
        marginBottom:5
    },
    textLeaderBoard:{
        fontSize:14,
        fontFamily:'BetmRoundedBold',
        color:'black',
        paddingLeft:2,
        paddingRight:2
    },
    textConnect:{
        fontSize:14,
        fontFamily:'BetmRoundedBold',
        color:'white',
        paddingLeft:2,
        paddingRight:2
    },
    btnLearderBoard:{
        backgroundColor:'#F8980C',
        borderBottomWidth:5,
        borderRightWidth:5,
        borderTopWidth:2,
        borderLeftWidth:2,
        borderColor:'black'
    },
    btnConnect:{
        backgroundColor:'#2C6ACA',
        borderBottomWidth:5,
        borderRightWidth:5,
        borderTopWidth:2,
        borderLeftWidth:2,
        borderColor:'black'
    },
    viewTropy:{
        borderBottomWidth:4,
        borderLeftWidth:4,
        borderRadius:4,
        borderRightWidth:4,
        borderTopWidth:4,
        borderColor:'#FD9505',
        marginLeft:7,
        marginBottom:10
    },
    iconTropy:{
        color:'#FD9505',
        fontSize:46,
        padding:3,
    },
    viewUser:{
        borderBottomWidth:4,
        borderLeftWidth:4,
        borderRadius:4,
        borderRightWidth:4,
        borderTopWidth:4,
        borderColor:'#C7CDCC',
        marginLeft:7,
    },
    iconUser:{
        color:'#C7CDCC',
        fontSize:50,
        padding:3
    },
    imageBackground:{
        flex:1,
        width:'100%',
        height:'100%'
    },
    colCombos:{
        justifyContent:'center',
        alignItems:'center'
    },
    viewCombos:{
        backgroundColor:'#FCFCFF',
        width:'40%',
        borderRadius:12,
        marginTop:12,
        padding:10,
        justifyContent:'center',
        alignItems:'center'
    },
    btnBama:{
        marginLeft:5,
        marginTop:-70,
        backgroundColor:'#2C76E3',
        height:80,
        width:80,
        justifyContent:'center'
    },
    btnBymi:{
        marginLeft:5,
        marginTop:-150,
        backgroundColor:'#D42926',
        height:80,
        width:80,
        justifyContent:'center'
    },
    btnShark:{
        marginLeft:5,
        marginTop:-70,
        backgroundColor:'#FF00F9',
        height:80,
        width:80,
        justifyContent:'center'
    },
    btnDu:{
        marginLeft:1,
        marginTop:-150,
        backgroundColor:'#FC9900',
        height:80,
        width:80,
        justifyContent:'center'
    }
})